### ISSUE TITLE
iKinCartesianSolver Segmentation Fault

### ISSUE THREAD

**Issue by yeshasvitirupachuri** [robotology/icub-tutorials#4]
Dear @pattacini, 

I am trying to used cartesian control with icub gazebo models. I followed the cartesian interface tutorial ( http://wiki.icub.org/brain/icub_cartesian_interface.html)

1) Launched Gazebo and inserted icub_with_hands model
2) simCartesianControl --robot icubGazeboSim (runs without errors)
3) iKinCartesianSolver   --robot icubGazeboSim --context simCartesianControl --part left_arm (this gives me a segmentation fault)  [log.txt](https://github.com/robotology/icub-tutorials/files/268680/log.txt)

Please let me know how to address this issue

Thank you

**Comment by pattacini** [comment]
Hi @Yeshasvitvs 

Honestly, I have no experience with Gazebo and it's also not easy for me to test it at the moment, given that Gazebo is not really multi-platform yet.

However, it doesn't seem there're problems to use Cartesian control in that environment: see e.g. https://github.com/robotology/QA/issues/115. Perhaps, @apostroph might help you out too.

Regarding the log you provided, there's a quite weird thing: the connection between the extended state ports (i.e. `stateExt`) took place far after the connections among the other ports of the same device driver. This is very suspicious and might indicate that the system is not in a _good shape_ in yarp sense.

**Comment by yeshasvitirupachuri** [comment]
@pattacini  regarding the yarp setup of the system could you please direct me where to look to check the weird connections. I followed the tutorials on installation for both yarp and icub

**Comment by jimmybaraglia** [comment]
Hi @Yeshasvitvs

Thank you @pattacini for tagging me here. I wish I could help more, but I just started using iCub Gazebo few days ago.
I tried to reproduce the error and did the same steps with you, but everything worked fine.
The difference maybe be that I modified "cartesianSolver.ini" so that the "robot" variable is set at "icubGazeboSim" there.

I will continue to test it and tell you if I find something else.

**Comment by pattacini** [comment]
@Yeshasvitvs the very first attempt I would do is to launch `iCub_SIM` (aka the old simulator) alongside with the Cartesian control suite while keeping an eye to the very same timing of those connections.

**Comment by yeshasvitirupachuri** [comment]
@pattacini I tried it with iCub_Sim and have the same problem of segmentation fault while running iKinCartesianSolver. Also no weird delay the connection between the extended state ports
[log_icubSim.txt](https://github.com/robotology/icub-tutorials/files/270170/log_icubSim.txt)

**Comment by pattacini** [comment]
How did you install/compile `yarp` and `icub-main` then?

Also, did you make sure that the binaries you're launching are the intended ones, rather than some outdated executable that are leftovers of old building processes?

I've just set up a virtual ubuntu xenial machine and everything works fine here.

**Comment by yeshasvitirupachuri** [comment]
@pattacini Sorry for the trouble. It was my bad that I did not install icub-common and there was a problem in linking to the ipopt library. I fixed it with help of @traversaro Thank you guys. Now everything works in gazebo.

**Comment by pattacini** [comment]
Glad to know you got it working.
Another great support from @traversaro :smiley:
